

var enardata = {   
    "success": "تم بنجاح",
    "delivery": "التوصيل",
    "scheduled": "وقت التوصيل",
    "2pm - 5pm": "2 م - 5 م",
    "pending": "قيد الانتظار",
    "8am - 2pm": "8 ص - 2 م",
    "cashondelivery": "الدفع عند الاستلام",
    "cancel": "الغاء",
    "accepted": "طلب مقبول",
    "cash": "كاش",
    "no orders found": "لم يتم أي طلب",
    "completed": "مكتمل",
    "delivery address": "عنوان التسليم",
    "delivery date": "تاريخ التسليم ",
    "contact info": "معلومات الاتصال",
    "items": "السلع",
    "total": "المجموع",
    "cancelled": "ملغي",
    "update": "تحديث",
    "enter first name": "أدخل الاسم الاول",
    "enter last name": "ادخل الاسم الاخير",
    "enter username": "ادخل اسم المستخدم",
    "enter password": "أدخل كلمة المرور",
    "password is not matching": "كلمة المرور غير متطابقة",
    "select usertype": "حدد نوع المستخدم",
    "name": "اسم",
    "total order": "اجمالي الطلبات ",
    "sub total": "المجموع",
    "discount": "تخفيض",
    "net amount": "قيمة الدخل",
    "pages": "الصفحات",
    "dashboard": "صفحة التحكم",
    "order": "طلب",
    "user": "مستخدم",
    "users": "المستخدمين",
    "report": "التقارير",
    "sales report": "تقرير المبيعات",
    "customer": "عميل",
    "customers": "عملاء",
    "voucher": "الخصم",
    "vouchers": "الخصومات",
    "products": "المنتجات",
    "slaughter": "المسلخ",
    "create": "انشاء",
    "confirm": "تاكيد",
    "net total": "اجمالي الدخل",
    "frozen": "المجمد",
    "fresh": "الطازج",
    "fresh eggs": "البيض الطازج",
    "pick your need": "المنتجات الامثل مع المتحدة ",
    "kuwait united poultry company": "الشركة الكويتية المتحدة للدواجن ",
    "choose your products": "اختر منتجاتك",
    "frozen products": "المنتجات المجمدة",
    "fresh products": "منتجات الطازجة",
    "enter mobile #": "ادخل رقم الهاتف",
    "enter your mobile number to continue the order": "أدخل رقم هاتفك لمتابعة الطلب",
    "customer info": "معلومات العميل",
    "if new, please fill below detail and continue next": "إذا كانت هذه التجربه الاولى معنا ، يرجى تعبئه البيانات التاليه للمتابعه",
    "fullname": "الاسم الكامل",
    "mobile #": " رقم الهاتف",
    "city": "المدينة",
    "block": "قطعه ",
    "street": "شارع",
    "building no #": "رقم المبنى",
    "note": "ملاحظات",
    "next": "التالي",
    "delivery place": "العنوان",
    "search": "بحث",
    "customer detail": "معلومات العميل",
    "customer name": "اسم  العميل",
    "address": "العنوان",
    "order detail": "تفاصيل الطلب",
    "coupen code": "رمز الكوبون",
    "delivery scheduled": "وقت الاستلام",
    "payment type": "نوع الدفع ",
    "confirm and pay": "التاكيد و الدفع",
    "cash on delivery": "الدفع عند الاستلام",
    "apply": "اضافه",
    "order confirm": "تاكيد الطلب",
    "back": "خلف",
    "checkout": "الدفع",
    "knet": "كي نت",
    "select product": " اختر منتج",
    "enter mobile number": "ادخل رقم الهاتف",
    "enter valid mobile number": "ادخل ىقم هاتف صحيح",
    "not exist": "لا يوجد بيانات على هذا الرقم",
    "enter name": "ادخل اسم المستخدم",
    "select address type": "ادخل نوع السكن",
    "enter block": "ادخل رقم القطعه",
    "enter street": "ادخل رقم الشارع",
    "enter building": "ادخل رقم المبنى",
    "select delivery place": "اختر نوع السكن",
    "enter apartment #": "ادخل رقم الشقه",
    "enter floor #": "اخل رقم الدور",
    "enter coupon code": "ادخل كود الخصم",
    "invalid coupen": " كود الخصم غير فعال",
    "order created successfuly. your order #": " تم تنفيذ الطلب بنجاح, رقم طلبك ",
    "login": "تسجيل الدخول ",
    "governorate": "المحافظة",
    "avenue": "رقم الجادة",
    "floor #": "رقم الدور",
    "apartment #": "رقم الشقه",
    "order less than 10 kd will not be delivered": "لا يمكن اتمام الطلبات اقل من 10 KD",
    "status": "الحالة",
    "failed": "فشل",
    "initiated": "ابدأ",
    "delivery charge": "تكلفة التوصيل",
    "product": "منتج",
    "product list": "قائمة المنتجات",
    "administration": "إدارة",
    "orderinfo": "بيانات الطلب",
    "schedule": "وقت التوصيل",
    "order for delivery not found": " Order For Delivery Not Found AR",
    "pickup": "Pickup AR",
    "complete": "مكتمل",
    "order info": "بيانات الطلب",
    "invoice reminder sent": "تم إرسال رابط الدفع بنجاح",
    "send payment link": "إرسال رابط الدفع",
    "driver cash": "سائق كاش",
    "please enter the name": " يرجى كتابة الاسم ",
    "please enter the address": "يرجى كتابة العنوان ",
    "please enter the username": " يرجى كتابة اسم المستخدم ",
    "please enter the password": " يرجى كتابة الرقم السري  ",
    "please select the city": " يرجى اختيار المنطقة",
    "please enter the block": " يرجى كتابة رقم القطعة",
    "please enter the street": " يرجى كتابة رقم الشارع",
    "please enter the building": " يرجى ادخال رقم المبنى",
    "order creation in process": "الطلب قيد الانشاء",
    "order created successfully. your order #": "تم انشاء الطلب بنجاح. رقم الطلب #",
    "invalid coupon": "الكوبون غير صحيح",
    "order less than 10 kd will not be delivered": "لن يتم تنفيذ أي طلب اقل من 10 دنانير",
    "offer start date": "تاريخ بداية الخصم",
    "offer end date": "تاريخ نهاية الخصم",
    "enter value or percent": "يرجى ادخال نسبة او قيمة",
    "order created by customer":"الطلب المنشأ عن طريق الزبون"
};

function getenar(a, b) {

    if (b == null)
        b = "en";

        if (b.toLowerCase() != "en") {
            var c = (a).toLowerCase();
            var d = enardata[c];

            if (d != null && d.length > 0) {
                return d;
            }
            return a;
        }

        return a;
    
   
}
